from gym.envs.registration import register

register(
        id='Gridworld-v0',
        entry_point='gym_gridworlds.envs:GridworldEnv',
        )
register(
        id='WindyGridworld-v0',
        entry_point='gym_gridworlds.envs:WindyGridworldEnv',
        )
register(
        id='Cliff-v0',
        entry_point='gym_gridworlds.envs:CliffEnv',
        )
register(
        id='DistractedCliff-v0',
        entry_point='gym_gridworlds.envs:DistractedCliffEnv',
        )
register(
        id='DistractedCliff-v1',
        entry_point='gym_gridworlds.envs:DistractedCliffEnv1',
        )
register(
        id='ExplorationGrid-v0',
        entry_point='gym_gridworlds.envs:ExplorationGrid',
        )
register(
        id='ExplorationGrid-v1',
        entry_point='gym_gridworlds.envs:ExplorationGrid1',
        )
